# Generated by Django 2.1 on 2019-07-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideoMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=10)),
                ('video_name', models.CharField(max_length=200)),
                ('video_size', models.IntegerField()),
            ],
        ),
    ]
