# Generated by Django 2.1 on 2019-07-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapi', '0002_auto_20190725_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('file_path', models.CharField(max_length=500)),
            ],
        ),
    ]
